version: '3.7'
services:
  api_service:
    image: "mansi11424/patient-api_service:latest"
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/localspringbootdb?allowPublicKeyRetrieval=true
#    depends_on:
#      - mysqldb
    volumes:
      - .m2:/root/.m2

#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3307:3306
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: localspringbootdb
#      MYSQL_ROOT_PASSWORD: Admin
#
#  history-mongodb:
#    image: mongo:latest
#    container_name: "history-mongodb"
#    ports:
#      - 27017:27017
#    volumes:
#      - mongodb_data:/data/db
#
#  springbootdockercompose:
#    image: springdockercompose:latest
#    container_name: "springdockercompose"
#    ports:
#      - 8082:8082
#    volumes:
#      - ./src/main:/src/main
#    depends_on:
#      - history-mongodb

#  patient-assessment:
#    image: patient-assessment:latest
#    ports:
#      - "8080:8080"
#    networks:
#      - springapimysql-net

networks:
  springapimysql-net:

volumes:
  mongodb_data:
